import java.util.ArrayList;

public class Pilotlar extends GrandPrix  {
    @Override
    ArrayList<String> bilgiGetir() {
        ArrayList<String> pilotIsimleri = new ArrayList<>();
        pilotIsimleri.add("Charles Leclerc");
        pilotIsimleri.add("Monaco");
        pilotIsimleri.add("0");
        pilotIsimleri.add("103");
        pilotIsimleri.add("Carlos Sainz");
        pilotIsimleri.add("Spain");
        pilotIsimleri.add("0");
        pilotIsimleri.add("163");
        pilotIsimleri.add("Sebastian Vettel");
        pilotIsimleri.add("Germany");
        pilotIsimleri.add("4");
        pilotIsimleri.add("300");
        pilotIsimleri.add("Lance Stroll");
        pilotIsimleri.add("Canada");
        pilotIsimleri.add("0");
        pilotIsimleri.add("122");
        pilotIsimleri.add("Valtteri Bottas");
        pilotIsimleri.add("Finland");
        pilotIsimleri.add("0");
        pilotIsimleri.add("200");
        pilotIsimleri.add("Zhou Guanyu");
        pilotIsimleri.add("China");
        pilotIsimleri.add("0");
        pilotIsimleri.add("22");
        pilotIsimleri.add("Max Verstappen");
        pilotIsimleri.add("Netherlands");
        pilotIsimleri.add("2");
        pilotIsimleri.add("163");
        pilotIsimleri.add("Sergio Perez");
        pilotIsimleri.add("Mexico");
        pilotIsimleri.add("0");
        pilotIsimleri.add("236");
        pilotIsimleri.add("Lewis Hamilton");
        pilotIsimleri.add("United Kingdom");
        pilotIsimleri.add("7");
        pilotIsimleri.add("310");
        pilotIsimleri.add("George Russell");
        pilotIsimleri.add("United Kingdom");
        pilotIsimleri.add("0");
        pilotIsimleri.add("82");
        pilotIsimleri.add("Fernando Alanso");
        pilotIsimleri.add("Spain");
        pilotIsimleri.add("2");
        pilotIsimleri.add("358");
        pilotIsimleri.add("Esteban Ocon");
        pilotIsimleri.add("France");
        pilotIsimleri.add("0");
        pilotIsimleri.add("111");
        pilotIsimleri.add("Daniel Ricciardo");
        pilotIsimleri.add("Australia");
        pilotIsimleri.add("0");
        pilotIsimleri.add("232");
        pilotIsimleri.add("Lando Norris");
        pilotIsimleri.add("United Kingdom");
        pilotIsimleri.add("0");
        pilotIsimleri.add("82");
        pilotIsimleri.add("Mick Schumacher");
        pilotIsimleri.add("Germany");
        pilotIsimleri.add("0");
        pilotIsimleri.add("43");
        pilotIsimleri.add("Kevin Magnussen");
        pilotIsimleri.add("Denmark");
        pilotIsimleri.add("0");
        pilotIsimleri.add("142");
        pilotIsimleri.add("Pierre Gasly");
        pilotIsimleri.add("France");
        pilotIsimleri.add("0");
        pilotIsimleri.add("108");
        pilotIsimleri.add("Yuki Tsunoda");
        pilotIsimleri.add("Japan");
        pilotIsimleri.add("0");
        pilotIsimleri.add("44");
        pilotIsimleri.add("Nicholas Latifi");
        pilotIsimleri.add("Canada");
        pilotIsimleri.add("0");
        pilotIsimleri.add("61");
        pilotIsimleri.add("Alexander Albon");
        pilotIsimleri.add("Thailand");
        pilotIsimleri.add("0");
        pilotIsimleri.add("59");
        return pilotIsimleri;
    }
}
